[package]
name = "fortress-client-wasm"
description = "The WASM project that handles the fortress-client UI"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
leptos = { version = "0.6.6", features = ["csr"] }
